Category.create!(name: "Canh")
Category.create!(name: "Đồ nướng")
Category.create!(name: "Lẩu")
Category.create!(name: "Đồ ăn nhanh")
Category.create!(name: "Piza")
Category.create!(name: "Đồ nấu chín")
